version: '3'

services:
  client:
    build: client
    ports:
      - 8501:8501
    depends_on:
      - server
    volumes:
      - ./storage:/storage

  server:
    build: server
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 16G
